#!/usr/bin/env bash
#looping 1 to 10 exept number 9 that says hi
counter=1

while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  counter=$(( counter + 1 ))
done

