#!/usr/bin/env bash
# Display hours from 0 to 12 with 59 minutes for each hour
hours=0

# Display hours from 0 to 12 with 59 minutes for each hour
while [ $hours -le 12 ]; do
  echo "Hour: $hours"
  minutes=1
  while [ $minutes -le 59 ]; do
    echo "$minutes"
    minutes=$((minutes + 1))
  done
  hours=$((hours + 1))
done

